const KOMIK = [
  {
    id: 0,
    judul: "When The System Opens After The Age Of 100, All Grandchildren Kneel Upon The Mountains!",
    cover: "https://i.postimg.cc/hjPrzPzg/When-The-System-Opens-After-The-Age-Of-100-193x278.webp",
    deskripsi: "Xiao Chen, seorang pelintas waktu yang hampir berusia seratus tahun, sedang bersiap-siap dengan tenang untuk menghabiskan sisa hidupnya. Tiba-tiba, sebuah sistem aktif, memberinya hadiah atas kelahiran anak dalam keluarganya. Tidak hanya kekuatannya akan meningkat, tetapi umurnya juga akan bertambah! 'Berkembang biak, cepat berkembang biak!' ucapnya. 'Semua anggota keluarga, tanpa memandang usia atau jenis kelamin, beranak, beranak, terus beranak!'",
    chapter: [
      {
        judul: "1",
        images: [
          "https://files.catbox.moe/q3cq1i.jpg",
          "https://files.catbox.moe/bouf9q.jpg",
          "https://files.catbox.moe/bz2vee.jpg",
          "https://files.catbox.moe/pqjtfz.jpg",
          "https://files.catbox.moe/bgjqtn.jpg",
          "https://files.catbox.moe/ia26z4.jpg",
          "https://files.catbox.moe/voa203.jpg",
          "https://files.catbox.moe/wkn1vn.jpg",
          "https://files.catbox.moe/on5z2b.jpg",
          "https://files.catbox.moe/aqh3q4.jpg",
          "https://files.catbox.moe/vmfoix.jpg",
          "https://files.catbox.moe/gk98fc.jpg",
          "https://files.catbox.moe/zeh5bg.jpg",
          "https://files.catbox.moe/omdaak.jpg",
          "https://files.catbox.moe/pfv7k7.jpg",
          "https://files.catbox.moe/ihk590.jpg",
          "https://files.catbox.moe/tllxqr.jpg",
          "https://files.catbox.moe/7i9ywo.jpg",
          "https://files.catbox.moe/86kowx.jpg",
          "https://files.catbox.moe/uwqtjh.jpg",
          "https://files.catbox.moe/8ojb9j.jpg",
          "https://files.catbox.moe/vk0tax.jpg",
          "https://files.catbox.moe/yetgby.jpg",
          "https://files.catbox.moe/of77yy.jpg",
          "https://files.catbox.moe/bot45r.jpg",
          "https://files.catbox.moe/e0xwua.jpg",
          "https://files.catbox.moe/njrjwg.jpg",
          "https://files.catbox.moe/sbx8g5.jpg",
          "https://files.catbox.moe/q0rox5.jpg",
          "https://files.catbox.moe/mm15pc.jpg",
          "https://files.catbox.moe/bbigzk.jpg",
          "https://files.catbox.moe/e8mjxh.jpg",
          "https://files.catbox.moe/yddcfl.jpg",
          "https://files.catbox.moe/j7fl4h.jpg",
          "https://files.catbox.moe/1t11f0.jpg",
          "https://files.catbox.moe/w7eqn2.jpg",
          "https://files.catbox.moe/9igvt9.jpg",
          "https://files.catbox.moe/c1yem9.jpg",
          "https://files.catbox.moe/34r5s4.jpg",
          "https://files.catbox.moe/fd4n27.jpg",
          "https://files.catbox.moe/l9yy90.jpg",
          "https://files.catbox.moe/9mu34s.jpg",
          "https://files.catbox.moe/5q755p.jpg",
          "https://files.catbox.moe/ypzusj.jpg",
          "https://files.catbox.moe/fzoaat.jpg",
          "https://files.catbox.moe/g05h8p.jpg",
          "https://files.catbox.moe/kyy5ma.jpg",
          "https://files.catbox.moe/jnpjx7.jpg",
          "https://files.catbox.moe/7y6eos.jpg",
          "https://files.catbox.moe/6ifiuz.jpg",
          "https://files.catbox.moe/i44u0k.jpg"
        ]
      },
      {
        judul: "2",
        images: [
          "https://files.catbox.moe/9reo71.jpg",
          "https://files.catbox.moe/spko2k.jpg",
          "https://files.catbox.moe/snctl4.jpg",
          "https://files.catbox.moe/w3q1l7.jpg",
          "https://files.catbox.moe/6b35kz.jpg",
          "https://files.catbox.moe/xnjixs.jpg",
          "https://files.catbox.moe/ehdhbi.jpg",
          "https://files.catbox.moe/0g57e2.jpg",
          "https://files.catbox.moe/wtyka3.jpg",
          "https://files.catbox.moe/w8yxn2.jpg",
          "https://files.catbox.moe/k5eyyg.jpg",
          "https://files.catbox.moe/ua2quy.jpg",
          "https://files.catbox.moe/9p4owl.jpg",
          "https://files.catbox.moe/1mej1m.jpg",
          "https://files.catbox.moe/m64262.jpg",
          "https://files.catbox.moe/grrq97.jpg",
          "https://files.catbox.moe/7p0md8.jpg",
          "https://files.catbox.moe/5ov94d.jpg",
          "https://files.catbox.moe/3efmb1.jpg",
          "https://files.catbox.moe/dm4qp7.jpg",
          "https://files.catbox.moe/b84m5m.jpg",
          "https://files.catbox.moe/esgokc.jpg",
          "https://files.catbox.moe/htl983.jpg",
          "https://files.catbox.moe/3s8475.jpg"
        ]
      },
            {
        judul: "3",
        images: [
          "https://files.catbox.moe/rlys0u.jpg",
          "https://files.catbox.moe/k2ii06.jpg",
          "https://files.catbox.moe/cbw592.jpg",
          "https://files.catbox.moe/5yqbhp.jpg",
          "https://files.catbox.moe/t03fvg.jpg",
          "https://files.catbox.moe/r8cztv.jpg",
          "https://files.catbox.moe/8pr1l3.jpg",
          "https://files.catbox.moe/8pwe3o.jpg",
          "https://files.catbox.moe/8mmtt2.jpg",
          "https://files.catbox.moe/madzpa.jpg",
          "https://files.catbox.moe/rvdr34.jpg",
          "https://files.catbox.moe/rcda4c.jpg",
          "https://files.catbox.moe/kn1oyu.jpg",
          "https://files.catbox.moe/x47aw6.jpg",
          "https://files.catbox.moe/cl86fd.jpg",
          "https://files.catbox.moe/e06691.jpg",
          "https://files.catbox.moe/90htrd.jpg",
          "https://files.catbox.moe/yu0fdc.jpg",
          "https://files.catbox.moe/1veyu6.jpg",
          "https://files.catbox.moe/hcqhpb.jpg",
          "https://files.catbox.moe/pwhcab.jpg",
          "https://files.catbox.moe/smt2c9.jpg",
          "https://files.catbox.moe/t6htan.jpg",
          "https://files.catbox.moe/1n7uya.jpg",
          "https://files.catbox.moe/kas50h.jpg",
          "https://files.catbox.moe/yt1z3d.jpg",
          "https://files.catbox.moe/mlrz3n.jpg"
        ]
      }
    ]
  }
];
